import LocalizedStrings from 'react-native-localization';


const STRINGS = new LocalizedStrings({
  "en": {
    appName: 'Reproduce',

    dummy: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua",
    genericErrorMsg: 'Opps! Something went wrong.',
    appExitMsg: 'Hold on!, Are you sure you want to go back?',
    logoutAlertTitle: 'Log out',
    logoutAlertMsg: 'Do you want to logout?',
    sessionExpiredTitle: 'Session Expired!',
    sessionExpiredMsg: 'Your session has been expired. Please login again to continue.',
    loginNotAllowed: 'You are not authorized to use this application',

    deletePopupTitle: 'Delete',
    deletePopupMsg: 'Are you sure, you want to delete ?',

    pickImgPopupTitle: 'Pick image',
    pickImgPopupMsg: 'Pick image from',
    noDataFound: 'No data found',

    //common
    btnYes: 'Yes',
    btnNo: 'No',
    btnOk: 'Ok',
    btnSkip: 'Skip',
    btnNext: 'Next',
    btnCancel: 'Cancel',
    btnUpdate: 'Update',
    btnSubmit: 'Submit',
    btnReset: 'Reset',
    btnContinue: 'Continue',
    btnDownload: 'Download',
    btnFavourite: 'Favourite',
    btnDetails: 'Details',
    btnView: 'View',
    btnEdit: 'Edit',
    btnDelete: 'Delete',
    btnRepost: 'Repost',
    btnCheckout: 'Checkout',
    btnContinueBrowsing: 'Continue Browsing',
    dropdownHint: 'Choose...',
    priceSymbol: '₹',
    to: 'To',

    btnGetStarted: 'Get Started',

    signinPageTitle: 'Signin',
    welcome: 'Welcome',
    signinToContinue: 'SIGN IN\nTO CONTINUE',
    email: 'Email',
    password: 'Password',
    rememberMe: 'Remember me',
    forgotPassword: 'Forgot password ?',
    lostPassword: 'Lost password ?',
    btnLogin: 'Login',
    btnRegister: 'Register',
    btnSignin: 'Signin',
    btnSignup: 'Signup',
    dontHaveAccount: "Don't have an account? ",


    signupPageTitle: 'Signup',
    createYourAccount: 'Create your account',
    userTypePatient: 'Patient',
    userTypeDoctor: 'Doctor',
    name: 'Name',
    email: 'Email',
    address: 'Address',
    phoneNo: 'Phone',
    password: 'Password',
    confPassword: 'Confirm Password',
    agreement: 'By creating an account you agree to our terms of service and privacy policy',
    alreadyHaveAccount: "Already have an account? ",
    userTypeEmptyMsg: 'Please choose user type',
    nameEmptyMsg: 'Please enter name',
    validPhoneNoMsg: 'Please enter a valid phone number',
    validEmailMsg: 'Please enter a valid email',
    addressEmptyMsg: 'Please enter address',
    passwordEmptyMsg: 'Please enter password',
    confPasswordEmptyMsg: 'Please confirm password',
    passwordNotMatchingMsg: 'Password is not same',

    verifyOtpPageTitle: 'OTP Verification',
    verifyOtpIntro: 'We have sent you a code to verify your mobile number',
    btnVerify: 'Verify',
    didntReceiveOTP: "I don't receive a code",
    btnResend: 'Resend',
    otpEmptyMsg: 'Please enter OTP',

    forgotPasswordPageTitle: 'Forgot password',
    forgotPasswordIntro: 'Enter your email address associated with your account. We will send you a link to reset your password',


    resetPasswordPageTitle: 'Reset password',
    resetPasswordIntro: 'Atleast 8 characters, with uppercase and lowercase letters',
    newPassword: 'New Password',
    confPassword: 'Confirm Password',


    tabHome: 'Home',
    tabProfile: 'Profile',
    tabAddProperty: 'Add',
    tabFavourite: 'Favourite',
    tabProperties: 'Properties',

    promoCode: 'Promo code',
    usePromoCode: 'Use promo code',
    myProfile: 'My Profile',
    myProperty: 'My Property',
    addProperty: 'Add Property',
    editProperty: 'Edit Property',
    bookedProperty: 'Booked Property',
    myEarning: 'My Earning',
    blogs: 'Blogs',
    termsNCondition: 'Terms & Condition',
    aboutUs: 'About Us',
    contactUs: 'Contact Us',
    career: 'Career',
    settings: 'Settings',

    subscription: 'Subscription',
    referAFriend: 'Refer a friend',
    giveUsFeedback: 'Give us feedback',
    needHelp: 'Need Help',
    logout: 'Logout',



    search: 'Search...',
    searchByLocation: 'Search by location',
    exclusiveForYou: 'Exclusive for you',
    // postedBy: 'Posted By',
    bookNow: 'Book now',
    btnViewDetails: 'View Details',
    propertyServices: 'Property Services',
    sweetHome: 'Sweet Home',
    bestService: 'Best Service',
    securePayment: 'Secure Payment',
    whyWeBest: 'Why we best',
    recommendedForYou: 'Recommended for you',

    searchPageTitle: 'Search',

    propertyLookingFor: 'Looking For',
    propertyPostingFor: 'Property For',
    propertyTitle: 'Property Title',
    description: 'Description',
    propertyLocation: 'Location',
    propertyType: 'Property Type',
    preference: 'Preference',
    bedrooms: 'Bedrooms',
    bathrooms: 'Bathrooms',
    floor: 'Floor',
    existFloor: 'Exist Floor',
    unit: 'Unit',
    carpetArea: 'Carpet Area(Sqft)',
    maintananceCharge: 'Maintanance Charge',
    carParking: 'Car Parking',
    furnishingStatus: 'Furnishing Status',
    positioningStatus: 'Positioning Status',
    availableFrom: 'Available From',
    actualPrice: 'Actual Price',
    bookingPrice: 'Booking Price',
    videoUrl: 'Video URL',
    propertyImages: 'Property Images',
    btnUploadImg: 'Upload Image',
    btnAddImg: 'Add Image',
    btnNearbyFacilities: 'Nearby Facilities',

    approvedPropertyCantEditMsg: "Approved Property Can't be edited",
    approvedPropertyCantDeleteMsg: "Approved Property Can't be deleted",
    propertyPostingForEmptyMsg: 'Please select Property Post Reason',
    propertyTitleEmptyMsg: 'Please enter Property Title',
    propertyDescriptionEmptyMsg: 'Please enter Property Description',
    propertyAddressEmptyMsg: 'Please enter Property Address',
    propertyLocationEmptyMsg: 'Please select Property Location',
    propertyTypeEmptyMsg: 'Please select Property Type',
    propertyPrefEmptyMsg: 'Please select Property Preference',
    noOfBedroomEmptyMsg: 'Please select no of Bedrooms',
    noOfBathroomEmptyMsg: 'Please select no of Bathrooms',
    floorEmptyMsg: 'Please select Property floor',
    existFloorEmptyMsg: 'Please select Floor Exists in the Building',
    carpetAreaEmptyMsg: 'Please enter Carpet Area',
    maintananceChargeEmptyMsg: 'Please enter Maintanance Charge',
    carParkingEmptyMsg: 'Please select Car Parking',
    furnishingStatusEmptyMsg: 'Please select Furnishing Status',
    positioningStatusEmptyMsg: 'Please select Positioning Status',
    availableFromEmptyMsg: 'Please select Available From',
    actualPriceEmptyMsg: 'Please select Actual Price',
    bookingPriceEmptyMsg: 'Please select Booking Price',
    videoUrlEmptyMsg: 'Please enter valid Video URL',
    propertyImagesEmptyMsg: 'Please enter Property Images',


    propertyDetails: 'Property Details',
    coveredArea: 'Covered Area',
    propertyAddress: 'Property Address',
    furnishing: 'Furnishing Details',
    configuration: 'Configuration',
    status: 'Status',
    constructionAge: 'Construction Age',
    btnBookNow: 'Book Now',
    btnCallBack: 'Call Back',
    btnRequestVisit: 'Request for Visit',
    btnSeeNearbyFacilities: 'See Nearby Facilities',
    relatedProperties: 'Related Properties',


    nearbyFacilities: 'Nearby Facilities',
    accessories: 'Home Decore & Accessories',
    rent: 'Rent',
    buy: 'Buy',

    checkout: 'Checkout',
    applyPromocode: 'Apply Promocode',
    enterPromocode: 'Enter Promocode',
    btnApply: 'Apply',
    orderStatus: 'Order Status',
    orderSummary: 'Order Summary',
    propertyPrice: 'Property Price',
    deliveryCharge: 'Delivery Charge',
    discount: 'Discount',
    gstCharge: 'GST Charge',
    totalAmount: 'Total Amount',
    emailInvoice: 'Email Invoice',


    filterPageTitle: 'Filters',
    localityOrLandmark: 'Locality/Landmark',
    budget: 'Budget',
    budgetMin: 'Min',
    budgetMax: 'Max',
    postedBy: 'Posted By',
    btnAddMore: 'Add More...',
    btnMoreFilters: 'More Filters',

    waitingForApproval: 'Waiting for approval',
    propertyBooked: 'Property booked',


    startDate: 'Start Date',
    endDate: 'End Date',
    amount: 'Amount',
    commission: 'Commission',
    totalAmount: 'Total Amount',


    selfAssesment: 'Self Assesment',
    dietRecommendation: 'Diet Recommendation',
    excerciseRecommendation: 'Excercise Recommendation',

  },

});

export default STRINGS;